# Generated by Django 3.1.3 on 2020-12-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201202_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imageURL',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
