# Generated by Django 3.1.3 on 2020-12-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201203_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imageURL',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile_image'),
        ),
    ]
