# Generated by Django 3.1.3 on 2021-01-10 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_profile_meditation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='meditation',
            field=models.ForeignKey(blank=True, default=' ', on_delete=django.db.models.deletion.CASCADE, to='main_app.meditation'),
        ),
    ]
