# Generated by Django 3.1.3 on 2021-01-10 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210110_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='meditation',
        ),
    ]
